(define (equal? a b)
  (cond ((and (null? b) (null? a)) #t)
  			((or (null? b) (null? a)) #f)
        ((and (pair? a) (pair? b)) (and (equal? (car a) (car b))
        																(equal? (cdr a) (cdr b))))
        ((or (pair? a) (pair? b)) #f)
      	(else (eq? a b))))